### PR TITLE
Update to version 4.2.0

### PR DESCRIPTION
**Pull request by awvwgk**
MNT: Re-rendered with conda-build 3.21.8, conda-smithy 3.19.0, and conda-forge-pinning 2022.04.23.18.15.26

Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* ~~Bumped the build number (if the version is unchanged)~~
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by vmagnin** [comment]
Thanks @awvwgk 
I had detected a few examples crashing only in macOS, and `examples\tests.f90` was one of them. It seems the problem comes from the GLib `g_get_os_info()` function, that I added in that example recently, line 556:
```
call c_f_string_copy(g_get_os_info("PRETTY_NAME"//c_null_char), os_string)
```
The doc (https://docs.gtk.org/glib/func.get_os_info.html) says it returns NULL if this information is not provided. That may be link to our problem.
I will try to fix it tomorrow. In the worst case I will remove that line which is not essential. Should I then make a 4.2.1 release so that you can relaunch the process?

**Comment by awvwgk** [comment]
Might be worth a patch release, it is certainly cleaner than just patching it in the recipe.

**Comment by vmagnin** [comment]
> Might be worth a patch release, it is certainly cleaner than just patching it in the recipe.

OK, I will work on it tomorrow. Thanks for help!

**Comment by vmagnin** [comment]
> Might be worth a patch release,

@awvwgk , I have fixed the issue https://github.com/vmagnin/gtk-fortran/issues/257 and made a patch release 4.2.1:
https://github.com/vmagnin/gtk-fortran/releases/tag/v4.2.1

**Pull request closed without merging**
